<Project Sdk="MSBuild.Sdk.Extras">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net35;net40;sl5</TargetFrameworks>
		<RootNamespace>IronRuby.Libraries</RootNamespace>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ruby\Ruby.csproj" />
		<ProjectReference Include="..\StdLib\StdLib.csproj" Condition=" '$(IncludeRubyStdLib)' == 'true' " />
	</ItemGroup>

	<Import Project="../../Build/sl5.props" Condition=" '$(TargetFramework)' == 'sl5' " />
	<Import Project="../../Build/net35.props" Condition=" '$(TargetFramework)' == 'net35' " />
	<Import Project="../../Build/net40.props" Condition=" '$(TargetFramework)' == 'net40' " />
	<Import Project="../../Build/netstandard2.0.props" Condition=" '$(TargetFramework)' == 'netstandard2.0' " />
</Project>