<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net35;net40;netstandard2.0</TargetFrameworks>
		<RootNamespace>IronRuby.Libraries</RootNamespace>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Ruby\Ruby.csproj" />
		<ProjectReference Include="..\StdLib\StdLib.csproj" Condition=" $(NoStdLib) != 'true' " />
	</ItemGroup>

	<Import Project="../../Build/net35.props" Condition=" '$(TargetFramework)' == 'net35' " />
	<Import Project="../../Build/net40.props" Condition=" '$(TargetFramework)' == 'net40' " />
	<Import Project="../../Build/netstandard2.0.props" Condition=" '$(TargetFramework)' == 'netstandard2.0' " />
</Project>