<Project Sdk="MSBuild.Sdk.Extras">
	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net35;net40;sl5</TargetFrameworks>

		<RootNamespace>IronRuby</RootNamespace>
		<AssemblyName>IronRuby</AssemblyName>

		<PackageId>IronRuby.Portable</PackageId>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<PropertyGroup>
		<NoWarn>NU5128</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<Compile Remove="Polyfills\Microsoft.Scripting.ComInterop\**" />
		<EmbeddedResource Remove="Polyfills\Microsoft.Scripting.ComInterop\**" />
		<None Remove="Polyfills\Microsoft.Scripting.ComInterop\**" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'sl5' or '$(TargetFramework)' == 'net35' or '$(TargetFramework)' == 'net40' ">
		<PackageReference Include="DynamicLanguageRuntime" Version="1.1.0-alpha1" />
	</ItemGroup>

	<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
		<PackageReference Include="DynamicLanguageRuntime" Version="1.2.3" />
		<PackageReference Include="System.Diagnostics.TraceSource" Version="4.3.0" />
		<PackageReference Include="System.Runtime.Numerics" Version="4.3.0" />
	</ItemGroup>

	<Import Project="../../Build/sl5.props" Condition=" '$(TargetFramework)' == 'sl5' " />
	<Import Project="../../Build/net35.props" Condition=" '$(TargetFramework)' == 'net35' " />
	<Import Project="../../Build/net40.props" Condition=" '$(TargetFramework)' == 'net40' " />
	<Import Project="../../Build/netstandard2.0.props" Condition=" '$(TargetFramework)' == 'netstandard2.0' " />
</Project>