<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>net35;net40;net7</TargetFrameworks>
		<RootNamespace>IronRuby</RootNamespace>
		<AssemblyName>ir</AssemblyName>

		<GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Libraries\IronRuby.Libraries.csproj" />
		<ProjectReference Include="..\Ruby\Ruby.csproj" />
	</ItemGroup>

	<Import Project="../../Build/net35.props" Condition=" '$(TargetFramework)' == 'net35' " />
	<Import Project="../../Build/net40.props" Condition=" '$(TargetFramework)' == 'net40' " />
	<Import Project="../../Build/netstandard2.0.props" Condition=" '$(TargetFramework)' == 'netstandard2.0' or '$(TargetFramework)' == 'net7' " />
</Project>